// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("Aaron Stannard")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2011-2016")]
[assembly: AssemblyVersionAttribute("2.0.0")]
[assembly: AssemblyFileVersionAttribute("2.0.0")]
